name: Build Library Interfaces

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt install -y cmake

      - name: Run bash script
        run: |
          chmod +x ./scripts/build_interfaces.bash
          ./scripts/build_interfaces.bash
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-lib-files
          path: |
            ./build/debug/lib
            ./build/release/lib
